name: docker-ci

# Quando for feito um push na branch main
on:
  push:
    branches:
      - main

# Executa essas verificações
jobs:
  # Faz um build da imagem para docker e envia para dockerhub
  # As variáveis de usuário e senha do dockerhub precisam ser configuradas no repositório do github para funcionar
  # Substituir a conta e nome da imagem
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU # name - descrição dessa etapa
        uses: docker/setup-qemu-action@v3 # Faz um setup do docker para funcionar em várias arquiteturas

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Permite que o docker consiga gerar o build das imagens

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5 # Faz o Build e da o push
        with:
          push: true
          tags: conta_dockerhub/nome_imagem:1.0 # endereço do dockerhub e nome da imagem
