name: Backend - Lint and Unit Tests Check

# Quando for feito um push na branch main
on:
  push:
    branches:
      - main

# Executar essas verificações
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Unit Tests
        run: yarn test

      - name: Lint Check
        run: yarn lint
